id: I88C857FB
legacy_id: P010569
ocr_import_info:
  bdrc_scan_id: W1KG12204
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T19:22:00'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:25:38.459945+00:00'
last_modified: 2022-08-31 11:25:47.287055
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12204
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12204
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསམ་གཟུགས་ཀྱི་མཐའ་དཔྱོད་ལེགས་བཤད་མཛོད་ཀྱི་སྒོ་འབྱེད།
  author: བསེ་ཚང ༠༡་ངག་དབང་བཀྲ་ཤིས།
statistics:
  ocr_word_mean_confidence_index: 0.5306085777248494
  ocr_word_median_confidence_index: 0.5
quality: null
bases:
  I1KG12258:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12258
      total_pages: 270
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12258.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5306085777248494
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
