id: P010569
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-20 10:14:32.852496
source_metadata:
  id: bdr:W1KG12204
  title: བསམ་གཟུགས་ཀྱི་མཐའ་དཔྱོད་ལེགས་བཤད་མཛོད་ཀྱི་སྒོ་འབྱེད།
  author: ''
  volumes:
    3e5377ada0c54a93af4871b8a7357759:
      image_group_id: I1KG12258
      title: ''
      volume_number: 1
      total_pages: 270
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
