id: P010569
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12204
  title: བསམ་གཟུགས་ཀྱི་མཐའ་དཔྱོད་ལེགས་བཤད་མཛོད་ཀྱི་སྒོ་འབྱེད།
  author: ''
  volumes:
    3e5377ada0c54a93af4871b8a7357759:
      image_group_id: I1KG12258
      title: ''
      volume_number: 1
      total_pages: 270
